"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Allcodes", [
      {
        type: "ROLE",
        keyMap: "R1",
        valueVi: "Quản trị viên",
        valueEn: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "ROLE",
        keyMap: "R2",
        valueVi: "Quản lý nhà hàng",
        valueEn: "Restaurent Manager",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "ROLE",
        keyMap: "R3",
        valueVi: "Khách hàng",
        valueEn: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T01",
        valueVi: "11:00",
        valueEn: "11:00 AM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T02",
        valueVi: "12:00",
        valueEn: "12:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T03",
        valueVi: "13:00",
        valueEn: "1:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T04",
        valueVi: "14:00",
        valueEn: "2:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T05",
        valueVi: "15:00",
        valueEn: "3:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T06",
        valueVi: "16:00",
        valueEn: "4:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T07",
        valueVi: "17:00",
        valueEn: "5:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T08",
        valueVi: "18:00",
        valueEn: "6:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T09",
        valueVi: "19:00",
        valueEn: "7:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T10",
        valueVi: "20:00",
        valueEn: "8:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T11",
        valueVi: "21:00",
        valueEn: "9:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "TIME",
        keyMap: "T12",
        valueVi: "22:00",
        valueEn: "10:00 PM",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "STATUS",
        keyMap: "S1",
        valueVi: "Lịch đặt mới",
        valueEn: "New",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "STATUS",
        keyMap: "S2",
        valueVi: "Đã xác thực email",
        valueEn: "Verified",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "STATUS",
        keyMap: "S3",
        valueVi: "Nhà hàng đã xác nhận",
        valueEn: "Confirmed",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "STATUS",
        keyMap: "S4",
        valueVi: "Đã ăn xong",
        valueEn: "Done",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "STATUS",
        keyMap: "S5",
        valueVi: "Đã hủy",
        valueEn: "Cancelled",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P1",
        valueVi: "Hà Nội",
        valueEn: "Ha Noi",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P2",
        valueVi: "Bắc Ninh",
        valueEn: "Bac Ninh",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P3",
        valueVi: "Hải Phòng",
        valueEn: "Hai Phong",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P4",
        valueVi: "Quảng Ninh",
        valueEn: "Quang Ninh",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P5",
        valueVi: "Đà Nẵng",
        valueEn: "Da Nang",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P6",
        valueVi: "Huế",
        valueEn: "Hue",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P7",
        valueVi: "Bà Rịa - Vũng Tàu",
        valueEn: "Ba Ria - Vung Tau",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P8",
        valueVi: "Đồng Nai",
        valueEn: "Dong Nai",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P9",
        valueVi: "Hồ Chí Minh",
        valueEn: "Ho Chi Minh",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "PROVINCE",
        keyMap: "P10",
        valueVi: "Cần Thơ",
        valueEn: "Can Tho",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "COUNTRY",
        keyMap: "C1",
        valueVi: "Việt Nam",
        valueEn: "Viet Nam",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "COUNTRY",
        keyMap: "C2",
        valueVi: "Nhật Bản",
        valueEn: "Japan",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "COUNTRY",
        keyMap: "C3",
        valueVi: "Hàn Quốc",
        valueEn: "Korea",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "COUNTRY",
        keyMap: "C4",
        valueVi: "Trung Quốc",
        valueEn: "China",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type: "COUNTRY",
        keyMap: "C5",
        valueVi: "Châu Âu",
        valueEn: "Europe",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Allcodes", null, {});
  },
};
